### ISSUE TITLE
Are the .env variables right?

### ISSUE THREAD

**Issue by rfay** [robertoperuzzo/ddev-sqlsrv#3]
I tried doing this on gitpod (for amd64) but had trouble with a number of things.

1. The .env variables shown don't seem to be everything I need, right? What's the username?
2. `MSSQL_HOST=localhost` isn't right, is it? Shouldn't it be `MSSQL_HOST=sqlsrv` ? 

What I was trying was manually doing a D9 install, but ran into things I didn't know how to do in the database setup screen.

**Comment by rfay** [comment]
With today's release still not able to get a Drupal install going on gitpod. "Failed to connect to your database server. The server reports the following message: SQLSTATE[28000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'Evaluation'.."

It's obvious I don't know the right things to put in there. 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/112444/230384590-97c403c5-1f50-4661-87b0-dfebbc7d99d5.png">

**Comment by robertoperuzzo** [comment]
Actually I never used an MSSQL database for Drupal. In one project of mine, I need to connect Drupal to an external MSSQL db, so that's why I need the sqlsrv PDO drivers. 

By the way, I'm going to test a Drupal installation on MSSQL.

**Comment by robertoperuzzo** [comment]
@rfay I applied the [patch #4](https://www.drupal.org/project/sqlsrv/issues/3291199) to the [module sqlsrv](https://www.drupal.org/project/sqlsrv) and I correctly installed the Drupal 9.5.7 on MS SQL server.

The credentials
<img width="668" alt="Screenshot 2023-04-08 at 11 08 04" src="https://user-images.githubusercontent.com/6221210/230804446-e9938851-58d7-4dc8-be43-89f41beae236.png">
The status page
<img width="1153" alt="Screenshot 2023-04-10 at 02 35 50" src="https://user-images.githubusercontent.com/6221210/230804468-88a682a9-86f4-4f96-8513-39406609ff51.png">
