### ISSUE TITLE
Tests (stable) error

### ISSUE THREAD

**Issue by robertoperuzzo** [robertoperuzzo/ddev-sqlsrv#9]
The [job tests (stable)](https://github.com/robertoperuzzo/ddev-sqlsrv/actions/runs/5229027832/jobs/9441758093) fail with the following error:

```
Run gautamkrishnar/keepalive-workflow@v1
  with:
    gh_token: ***
    commit_message: Automated commit by Keepalive Workflow to keep the repository active
    committer_username: gkr-bot
    committer_email: gkr-bot@tuta.io
    time_elapsed: 50
    auto_push: true
  env:
    NIGHTLY_DDEV_PR_URL: https://nightly.link/ddev/ddev/actions/runs/1720215802/ddev-linux-amd64.zip
    DDEV_GITHUB_TOKEN: ***
    HOMEBREW_NO_INSTALL_FROM_API: 1
Error: {"command":"git push origin HEAD","exitCode":128,"outputData":"","errorData":"remote: Permission to robertoperuzzo/ddev-sqlsrv.git denied to github-actions[bot].\nfatal: unable to access 'https://github.com/robertoperuzzo/ddev-sqlsrv.git/': The requested URL returned error: 403\n"}
```

**Comment by rfay** [comment]
Hmm, this is working OK elsewhere. It looks like this has already failed 4 days in a row though.

**Comment by rfay** [comment]
I recommend opening an issue in https://github.com/robertoperuzzo/ddev-sqlsrv/issues/ - it's sure not clear to me what's going on. Also, run it manually.

**Comment by tyler36** [comment]
I'm getting the same error on 
- [ddev-tinker](https://github.com/tyler36/ddev-tinker/actions)
- [ddev-cron](https://github.com/tyler36/ddev-cron/actions)

[ddev-vscode-devcontainer](https://github.com/tyler36/ddev-vscode-devcontainer/actions) also started but after making a commit, the scheduled tests started passing.

**Comment by rfay** [comment]
I see things like [ddev-drupal9-solr](https://github.com/ddev/ddev-drupal9-solr/actions) continuing as always. I do wonder if it's something changed about the power of the default github token or the configuration of the project.

**Comment by rfay** [comment]
@tyler36 I changed your role on ddev-drupal9-solr to admin so you can have full privs to try to compare it to the projects that are failing, thanks!

And of course compare the current version of https://github.com/gautamkrishnar/keepalive-workflow

**Comment by tyler36** [comment]
Perhaps Github changed something to prevent actions like keepalive from working around their cutoff.

**Comment by rfay** [comment]
That may be. But  I would think it would be affecting everything by now, and I haven't seen it on the ones I maintain. Good reason for an issue in https://github.com/gautamkrishnar/keepalive-workflow

**Comment by robertoperuzzo** [comment]
@tyler36 I did the same update as you [here](https://github.com/tyler36/ddev-tinker/pull/1/files) and the keepalive is back to work.

I close this issue.

**Comment by robertoperuzzo** [comment]
Thank you @rfay for your supervision!

Now the [scheduled test action](https://github.com/robertoperuzzo/ddev-sqlsrv/actions/runs/5253114152) has successfully rerun, is it a sign that it is fixed, or not?
Probably I miss something ;)

**Comment by rfay** [comment]
Thanks so much for maintaining this!

The problem here is that the job of this is to push a commit, and that's what failed (it wasn't the action/workflow itself). But it only does it after `time_elapsed` days without a commit.  you just did a commit. So it's a given that for the next 50 days this will succeed (that's the default `time_elapsed` in there, see https://github.com/gautamkrishnar/keepalive-workflow#for-github-action). If you want to prove that it's going to work now sooner, you can temporarily change the `time_elapsed` to 1 for example and wait a couple of days.
